language: node_js
sudo: enabled
install:
- sudo apt-get install -y sshpass zip curl git
script:
- git --version
- sshpass -V
- zip --version
- unzip  -version
- curl --version
- git ls-files
deploy:
  provider: script
  script:
    bash ./deploy.sh
  on:
    branch: master
    repo: devlato/devlato.com
after_deploy:
- curl -X GET $HEALTHCHECK_URL
notifications:
  email:
    recipients:
      - github@devlato.com
    on_success: always
    on_failure: always
