language: node_js
sudo: enabled
install:
- sudo apt-get install -y sshpass zip curl git
script:
- git --version
- sshpass -V
- zip --version
- unzip  -version
- curl --version
- git ls-files
deploy:
  provider: script
  script:
    bash ./deploy.sh
  on:
    tags: true
    repo: devlato/devlato.com
notifications:
  email:
    recipients:
      - $NOTIFICATION_EMAIL
    on_success: always
    on_failure: always
